"""Sensitive cookie export/import without logging session values."""
from pathlib import Path
import json
import logging
import math
from .utils import dola_domain, now, write_private, read_json

log = logging.getLogger(__name__)
WARNING = "Exported browser cookies may contain active login sessions. Store these files securely and never share them publicly."


def validate_cookies(value: object, dola_only: bool = False) -> list[dict]:
    if not isinstance(value, list):
        raise ValueError("Cookies must be a JSON array.")
    for cookie in value:
        if not isinstance(cookie, dict) or not all(isinstance(cookie.get(k), str) for k in ("name", "value", "domain", "path")):
            raise ValueError("Invalid cookie entry.")
        if not cookie["domain"] or not cookie["path"].startswith("/"):
            raise ValueError("Invalid cookie domain or path.")
        if dola_only and not dola_domain(cookie["domain"]):
            raise ValueError("Cookie imports must contain only Dola.com cookies.")
        if "expires" in cookie and (type(cookie["expires"]) not in (int, float) or not math.isfinite(cookie["expires"])):
            raise ValueError("Invalid cookie expiry.")
        for k in ("secure", "httpOnly"):
            if k in cookie and not isinstance(cookie[k], bool):
                raise ValueError("Invalid cookie flag.")
        if "sameSite" in cookie and cookie["sameSite"] not in ("Lax", "Strict", "None"):
            raise ValueError("Invalid SameSite value.")
    return value


def export_cookies(
    profile,
    cookies: list[dict],
    path: Path,
    format: str,
    overwrite: bool = False,
    dola_only: bool = True,
) -> None:
    """Write cookies without logging their values.

    Dola-only is the default for the selected-profile workflow. Bulk export can
    explicitly opt into all domains after the user sees the sensitive-data warning.
    """
    if dola_only:
        cookies = [cookie for cookie in cookies if dola_domain(cookie["domain"])]
    if dola_only and not cookies:
        raise ValueError("No Dola.com cookies found in this profile.")
    website = "dola.com" if dola_only else "all browser domains"
    payload = {"profile_name": profile.name, "browser": profile.browser, "website": website, "exported_at": now(), "cookies": cookies}
    if format == "JSON":
        text = json.dumps(payload, indent=2, ensure_ascii=False, allow_nan=False)
    elif format == "TXT":
        heading = "Dola.com Cookie Export" if dola_only else "Browser Cookie Export"
        lines = [heading, "=" * len(heading), f"Profile: {profile.name}", f"Browser: {profile.browser}", f"Website: {website}", f"Exported: {payload['exported_at']}"]
        for index, cookie in enumerate(cookies, 1):
            lines += ["", "-" * 50, f"COOKIE {index}", "-" * 50]
            lines += [f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in cookie.items()]
        text = "\n".join(lines) + "\n"
    elif format == "NETSCAPE":
        # Portable seven-column Netscape/curl cookie-jar format. JSON remains
        # the full-fidelity export for attributes this standard cannot carry.
        lines = ["# Netscape HTTP Cookie File", "# https://curl.se/docs/http-cookies.html", "# Generated by Dola Profile Manager.", ""]
        for cookie in cookies:
            expires = cookie.get("expires", 0)
            expires = 0 if expires is None or expires < 0 else int(expires)
            lines.append("\t".join((
                cookie["domain"],
                "TRUE" if cookie["domain"].startswith(".") else "FALSE",
                cookie["path"],
                "TRUE" if cookie.get("secure", False) else "FALSE",
                str(expires),
                cookie["name"],
                cookie["value"],
            )))
        text = "\n".join(lines) + "\n"
    else:
        raise ValueError("Choose JSON, TXT, or NETSCAPE.")
    write_private(path, text, overwrite)
    log.info("Cookie export completed: %s", profile.id)


def load_cookies(path: Path) -> list[dict]:
    value = read_json(path)
    if isinstance(value, dict):
        value = value.get("cookies")
    return validate_cookies(value, dola_only=True)
